import Link from "next/link";
import { ArrowUpRight, ExternalLink, Github } from "lucide-react";
import { projects } from "@/data/projects";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Reveal } from "@/components/reveal";
import { SectionHeading } from "@/components/section-heading";
import { ProjectVisual } from "@/components/project-visual";

export function Projects() { return <section id="projects" className="section-shell"><Reveal><SectionHeading eyebrow="03 / Selected work" title="Projects built around real problems." copy="Seven product-focused builds spanning property operations, applied AI, professional services, and real-time platforms." /></Reveal><div className="space-y-8">{projects.map((project, index) => <Reveal key={project.slug}><article className="group grid overflow-hidden border border-border bg-card shadow-soft lg:grid-cols-2"><ProjectVisual tone={project.tone} image={project.thumbnail} /><div className="flex flex-col p-6 sm:p-8"><div className="mb-8 flex items-center justify-between"><span className="font-mono text-xs text-primary">0{index + 1}</span><span className="text-xs uppercase text-muted-foreground">{project.eyebrow}</span></div><h3 className="text-2xl font-semibold sm:text-3xl">{project.title}</h3><p className="mt-4 leading-7 text-muted-foreground">{project.description}</p><div className="mt-6 flex flex-wrap gap-2">{project.technologies.slice(0, 6).map((tech) => <Badge key={tech}>{tech}</Badge>)}</div><div className="mt-8 flex flex-wrap gap-2 lg:mt-auto lg:pt-8"><Button asChild><Link href={`/projects/${project.slug}`}>View case study <ArrowUpRight className="size-4" /></Link></Button>{project.github && <Button asChild variant="outline"><a href={project.github}><Github className="size-4" />GitHub</a></Button>}{project.live && <Button asChild variant="outline"><a href={project.live}><ExternalLink className="size-4" />Live demo</a></Button>}</div></div></article></Reveal>)}</div></section>; }
